name: CI Prod - simple pull
on:
  push:             # Triggers automatically when code is pushed
    branches: [main]
  #workflow_dispatch: # Triggers a manual button in the GitHub UI

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    #env:
      #ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: ${{ vars.ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION }}
      
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Configure Git to use Personal Access Token
        run: |
          git config --global url."https://${{ secrets.PAT_BUANG_REV1 }}@github.com/".insteadOf "https://github.com/"

      - name: Execute Remote SSH Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            mkdir /home/umkacid/public_html/e-info
            cd /home/umkacid/public_html/e-info
            git config --global credential.helper store
            git remote set-url origin https://github.com/MuriaKudusUniverse/e-info.git
            git config --global url."https://buangyulianto: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@github.com".insteadOf "https://github.com"
            git pull origin main
            mv .htaccess-orig .htaccess
            chown -R umkacid:umkacid ./e-info
            
      - name: Run a text script
        run: echo "The GitHub Action is running successfully!"
